# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize
# Sync Directory
SDIR=~/Dropbox\ (Personal)/Apps/dotfiles

# Load Z Jump
. $SDIR/shell/aliases
. $SDIR/shell/archey/bin/archey -c
. $SDIR/shell/z/z.sh
. ~/.nvm/nvm.sh

# Load Rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
